/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowFlowIdRouteImport } from './routes/flow.$flowId'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowFlowIdRoute = FlowFlowIdRouteImport.update({
  id: '/flow/$flowId',
  path: '/flow/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/home': typeof HomeRoute
  '/new': typeof NewRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/home': typeof HomeRoute
  '/new': typeof NewRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/home': typeof HomeRoute
  '/new': typeof NewRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/credentials' | '/home' | '/new' | '/flow/$flowId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/credentials' | '/home' | '/new' | '/flow/$flowId'
  id: '__root__' | '/' | '/credentials' | '/home' | '/new' | '/flow/$flowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CredentialsRoute: typeof CredentialsRoute
  HomeRoute: typeof HomeRoute
  NewRoute: typeof NewRoute
  FlowFlowIdRoute: typeof FlowFlowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/$flowId': {
      id: '/flow/$flowId'
      path: '/flow/$flowId'
      fullPath: '/flow/$flowId'
      preLoaderRoute: typeof FlowFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CredentialsRoute: CredentialsRoute,
  HomeRoute: HomeRoute,
  NewRoute: NewRoute,
  FlowFlowIdRoute: FlowFlowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
