# Railway configuration for NodeX API deployment
[build]
builder = "dockerfile"
dockerfilePath = "docker-compose.yml"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3